services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
        - database

  api-prod:
    image: arsb29/gift-app:latest
    restart: always
    volumes:
      - .:/usr/src/app
      - ./assets:/usr/src/app/assets
      - /etc/letsencrypt/live/giftapp.space/fullchain.pem:/etc/letsencrypt/live/giftapp.space/fullchain.pem
      - /etc/letsencrypt/live/giftapp.space/privkey.pem:/etc/letsencrypt/live/giftapp.space/privkey.pem
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    command:
      - --auth
    ports:
      - '27017:27017'
    volumes:
      - './data:/data/db'